// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=../../mocks/mock_roomService.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/meshyampratap01/letStayInn/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockIRoomService is a mock of IRoomService interface.
type MockIRoomService struct {
	ctrl     *gomock.Controller
	recorder *MockIRoomServiceMockRecorder
	isgomock struct{}
}

// MockIRoomServiceMockRecorder is the mock recorder for MockIRoomService.
type MockIRoomServiceMockRecorder struct {
	mock *MockIRoomService
}

// NewMockIRoomService creates a new mock instance.
func NewMockIRoomService(ctrl *gomock.Controller) *MockIRoomService {
	mock := &MockIRoomService{ctrl: ctrl}
	mock.recorder = &MockIRoomServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRoomService) EXPECT() *MockIRoomServiceMockRecorder {
	return m.recorder
}

// AddRoom mocks base method.
func (m *MockIRoomService) AddRoom(number int, roomType string, price float64, isAvailable bool, description string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRoom", number, roomType, price, isAvailable, description)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRoom indicates an expected call of AddRoom.
func (mr *MockIRoomServiceMockRecorder) AddRoom(number, roomType, price, isAvailable, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRoom", reflect.TypeOf((*MockIRoomService)(nil).AddRoom), number, roomType, price, isAvailable, description)
}

// DeleteRoom mocks base method.
func (m *MockIRoomService) DeleteRoom(number int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRoom", number)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRoom indicates an expected call of DeleteRoom.
func (mr *MockIRoomServiceMockRecorder) DeleteRoom(number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRoom", reflect.TypeOf((*MockIRoomService)(nil).DeleteRoom), number)
}

// GetAllRooms mocks base method.
func (m *MockIRoomService) GetAllRooms() ([]models.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllRooms")
	ret0, _ := ret[0].([]models.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllRooms indicates an expected call of GetAllRooms.
func (mr *MockIRoomServiceMockRecorder) GetAllRooms() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllRooms", reflect.TypeOf((*MockIRoomService)(nil).GetAllRooms))
}

// GetAvailableRooms mocks base method.
func (m *MockIRoomService) GetAvailableRooms() ([]models.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableRooms")
	ret0, _ := ret[0].([]models.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableRooms indicates an expected call of GetAvailableRooms.
func (mr *MockIRoomServiceMockRecorder) GetAvailableRooms() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableRooms", reflect.TypeOf((*MockIRoomService)(nil).GetAvailableRooms))
}

// GetTotalAvailableRooms mocks base method.
func (m *MockIRoomService) GetTotalAvailableRooms() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalAvailableRooms")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalAvailableRooms indicates an expected call of GetTotalAvailableRooms.
func (mr *MockIRoomServiceMockRecorder) GetTotalAvailableRooms() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalAvailableRooms", reflect.TypeOf((*MockIRoomService)(nil).GetTotalAvailableRooms))
}

// GetTotalRooms mocks base method.
func (m *MockIRoomService) GetTotalRooms() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalRooms")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalRooms indicates an expected call of GetTotalRooms.
func (mr *MockIRoomServiceMockRecorder) GetTotalRooms() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalRooms", reflect.TypeOf((*MockIRoomService)(nil).GetTotalRooms))
}

// RoomExists mocks base method.
func (m *MockIRoomService) RoomExists(number int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoomExists", number)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RoomExists indicates an expected call of RoomExists.
func (mr *MockIRoomServiceMockRecorder) RoomExists(number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoomExists", reflect.TypeOf((*MockIRoomService)(nil).RoomExists), number)
}

// UpdateRoom mocks base method.
func (m *MockIRoomService) UpdateRoom(number, choice int, roomType string, price float64, isAvailable bool, description string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRoom", number, choice, roomType, price, isAvailable, description)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRoom indicates an expected call of UpdateRoom.
func (mr *MockIRoomServiceMockRecorder) UpdateRoom(number, choice, roomType, price, isAvailable, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRoom", reflect.TypeOf((*MockIRoomService)(nil).UpdateRoom), number, choice, roomType, price, isAvailable, description)
}
