// Code generated by MockGen. DO NOT EDIT.
// Source: interface1.go
//
// Generated by this command:
//
//	mockgen -source=interface1.go -destination=../../mocks/mock_serviceRequestService.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/meshyampratap01/letStayInn/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockIServiceRequestService is a mock of IServiceRequestService interface.
type MockIServiceRequestService struct {
	ctrl     *gomock.Controller
	recorder *MockIServiceRequestServiceMockRecorder
	isgomock struct{}
}

// MockIServiceRequestServiceMockRecorder is the mock recorder for MockIServiceRequestService.
type MockIServiceRequestServiceMockRecorder struct {
	mock *MockIServiceRequestService
}

// NewMockIServiceRequestService creates a new mock instance.
func NewMockIServiceRequestService(ctrl *gomock.Controller) *MockIServiceRequestService {
	mock := &MockIServiceRequestService{ctrl: ctrl}
	mock.recorder = &MockIServiceRequestServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIServiceRequestService) EXPECT() *MockIServiceRequestServiceMockRecorder {
	return m.recorder
}

// CancelServiceRequestByID mocks base method.
func (m *MockIServiceRequestService) CancelServiceRequestByID(reqID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelServiceRequestByID", reqID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelServiceRequestByID indicates an expected call of CancelServiceRequestByID.
func (mr *MockIServiceRequestServiceMockRecorder) CancelServiceRequestByID(reqID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelServiceRequestByID", reflect.TypeOf((*MockIServiceRequestService)(nil).CancelServiceRequestByID), reqID)
}

// GetPendingRequestCount mocks base method.
func (m *MockIServiceRequestService) GetPendingRequestCount() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingRequestCount")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingRequestCount indicates an expected call of GetPendingRequestCount.
func (mr *MockIServiceRequestServiceMockRecorder) GetPendingRequestCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingRequestCount", reflect.TypeOf((*MockIServiceRequestService)(nil).GetPendingRequestCount))
}

// GetUnassignedServiceRequest mocks base method.
func (m *MockIServiceRequestService) GetUnassignedServiceRequest() ([]models.ServiceRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnassignedServiceRequest")
	ret0, _ := ret[0].([]models.ServiceRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnassignedServiceRequest indicates an expected call of GetUnassignedServiceRequest.
func (mr *MockIServiceRequestServiceMockRecorder) GetUnassignedServiceRequest() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnassignedServiceRequest", reflect.TypeOf((*MockIServiceRequestService)(nil).GetUnassignedServiceRequest))
}

// ServiceRequestGetter mocks base method.
func (m *MockIServiceRequestService) ServiceRequestGetter(arg0 context.Context, arg1 int, arg2 models.ServiceType, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServiceRequestGetter", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// ServiceRequestGetter indicates an expected call of ServiceRequestGetter.
func (mr *MockIServiceRequestServiceMockRecorder) ServiceRequestGetter(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServiceRequestGetter", reflect.TypeOf((*MockIServiceRequestService)(nil).ServiceRequestGetter), arg0, arg1, arg2, arg3)
}

// UpdateServiceRequestAssignment mocks base method.
func (m *MockIServiceRequestService) UpdateServiceRequestAssignment(reqID string, isAssigned bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateServiceRequestAssignment", reqID, isAssigned)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateServiceRequestAssignment indicates an expected call of UpdateServiceRequestAssignment.
func (mr *MockIServiceRequestServiceMockRecorder) UpdateServiceRequestAssignment(reqID, isAssigned any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateServiceRequestAssignment", reflect.TypeOf((*MockIServiceRequestService)(nil).UpdateServiceRequestAssignment), reqID, isAssigned)
}

// UpdateServiceRequestStatus mocks base method.
func (m *MockIServiceRequestService) UpdateServiceRequestStatus(reqID string, status models.ServiceStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateServiceRequestStatus", reqID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateServiceRequestStatus indicates an expected call of UpdateServiceRequestStatus.
func (mr *MockIServiceRequestServiceMockRecorder) UpdateServiceRequestStatus(reqID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateServiceRequestStatus", reflect.TypeOf((*MockIServiceRequestService)(nil).UpdateServiceRequestStatus), reqID, status)
}
