// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=../../mocks/mock_feedbackService.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIFeedbackService is a mock of IFeedbackService interface.
type MockIFeedbackService struct {
	ctrl     *gomock.Controller
	recorder *MockIFeedbackServiceMockRecorder
	isgomock struct{}
}

// MockIFeedbackServiceMockRecorder is the mock recorder for MockIFeedbackService.
type MockIFeedbackServiceMockRecorder struct {
	mock *MockIFeedbackService
}

// NewMockIFeedbackService creates a new mock instance.
func NewMockIFeedbackService(ctrl *gomock.Controller) *MockIFeedbackService {
	mock := &MockIFeedbackService{ctrl: ctrl}
	mock.recorder = &MockIFeedbackServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIFeedbackService) EXPECT() *MockIFeedbackServiceMockRecorder {
	return m.recorder
}

// SubmitFeedback mocks base method.
func (m *MockIFeedbackService) SubmitFeedback(ctx context.Context, message string, rating int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmitFeedback", ctx, message, rating)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubmitFeedback indicates an expected call of SubmitFeedback.
func (mr *MockIFeedbackServiceMockRecorder) SubmitFeedback(ctx, message, rating any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitFeedback", reflect.TypeOf((*MockIFeedbackService)(nil).SubmitFeedback), ctx, message, rating)
}
