// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=../../mocks/mock_bookingRepository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/meshyampratap01/letStayInn/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockBookingRepository is a mock of BookingRepository interface.
type MockBookingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBookingRepositoryMockRecorder
	isgomock struct{}
}

// MockBookingRepositoryMockRecorder is the mock recorder for MockBookingRepository.
type MockBookingRepositoryMockRecorder struct {
	mock *MockBookingRepository
}

// NewMockBookingRepository creates a new mock instance.
func NewMockBookingRepository(ctrl *gomock.Controller) *MockBookingRepository {
	mock := &MockBookingRepository{ctrl: ctrl}
	mock.recorder = &MockBookingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookingRepository) EXPECT() *MockBookingRepositoryMockRecorder {
	return m.recorder
}

// CheckRoomBooked mocks base method.
func (m *MockBookingRepository) CheckRoomBooked(roomNumber int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckRoomBooked", roomNumber)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckRoomBooked indicates an expected call of CheckRoomBooked.
func (mr *MockBookingRepositoryMockRecorder) CheckRoomBooked(roomNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckRoomBooked", reflect.TypeOf((*MockBookingRepository)(nil).CheckRoomBooked), roomNumber)
}

// GetActiveBookings mocks base method.
func (m *MockBookingRepository) GetActiveBookings() ([]models.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveBookings")
	ret0, _ := ret[0].([]models.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveBookings indicates an expected call of GetActiveBookings.
func (mr *MockBookingRepositoryMockRecorder) GetActiveBookings() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveBookings", reflect.TypeOf((*MockBookingRepository)(nil).GetActiveBookings))
}

// GetAllBookings mocks base method.
func (m *MockBookingRepository) GetAllBookings() ([]models.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllBookings")
	ret0, _ := ret[0].([]models.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllBookings indicates an expected call of GetAllBookings.
func (mr *MockBookingRepositoryMockRecorder) GetAllBookings() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBookings", reflect.TypeOf((*MockBookingRepository)(nil).GetAllBookings))
}

// GetBookingByID mocks base method.
func (m *MockBookingRepository) GetBookingByID(arg0 string) (*models.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookingByID", arg0)
	ret0, _ := ret[0].(*models.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookingByID indicates an expected call of GetBookingByID.
func (mr *MockBookingRepositoryMockRecorder) GetBookingByID(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingByID", reflect.TypeOf((*MockBookingRepository)(nil).GetBookingByID), arg0)
}

// GetBookingsByUserID mocks base method.
func (m *MockBookingRepository) GetBookingsByUserID(userID string) ([]models.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookingsByUserID", userID)
	ret0, _ := ret[0].([]models.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookingsByUserID indicates an expected call of GetBookingsByUserID.
func (mr *MockBookingRepositoryMockRecorder) GetBookingsByUserID(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingsByUserID", reflect.TypeOf((*MockBookingRepository)(nil).GetBookingsByUserID), userID)
}

// SaveBookings mocks base method.
func (m *MockBookingRepository) SaveBookings(bookings []models.Booking) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveBookings", bookings)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveBookings indicates an expected call of SaveBookings.
func (mr *MockBookingRepositoryMockRecorder) SaveBookings(bookings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBookings", reflect.TypeOf((*MockBookingRepository)(nil).SaveBookings), bookings)
}

// UpdateBooking mocks base method.
func (m *MockBookingRepository) UpdateBooking(updated models.Booking) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBooking", updated)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBooking indicates an expected call of UpdateBooking.
func (mr *MockBookingRepositoryMockRecorder) UpdateBooking(updated any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBooking", reflect.TypeOf((*MockBookingRepository)(nil).UpdateBooking), updated)
}
