// Code generated by MockGen. DO NOT EDIT.
// Source: interface1.go
//
// Generated by this command:
//
//	mockgen -source=interface1.go -destination=../../mocks/mock_managerService.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/meshyampratap01/letStayInn/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockIManagerService is a mock of IManagerService interface.
type MockIManagerService struct {
	ctrl     *gomock.Controller
	recorder *MockIManagerServiceMockRecorder
	isgomock struct{}
}

// MockIManagerServiceMockRecorder is the mock recorder for MockIManagerService.
type MockIManagerServiceMockRecorder struct {
	mock *MockIManagerService
}

// NewMockIManagerService creates a new mock instance.
func NewMockIManagerService(ctrl *gomock.Controller) *MockIManagerService {
	mock := &MockIManagerService{ctrl: ctrl}
	mock.recorder = &MockIManagerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIManagerService) EXPECT() *MockIManagerServiceMockRecorder {
	return m.recorder
}

// AssignServiceRequest mocks base method.
func (m *MockIManagerService) AssignServiceRequest(reqID, empID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignServiceRequest", reqID, empID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignServiceRequest indicates an expected call of AssignServiceRequest.
func (mr *MockIManagerServiceMockRecorder) AssignServiceRequest(reqID, empID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignServiceRequest", reflect.TypeOf((*MockIManagerService)(nil).AssignServiceRequest), reqID, empID)
}

// DeleteEmployeeByID mocks base method.
func (m *MockIManagerService) DeleteEmployeeByID(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEmployeeByID", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEmployeeByID indicates an expected call of DeleteEmployeeByID.
func (mr *MockIManagerServiceMockRecorder) DeleteEmployeeByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEmployeeByID", reflect.TypeOf((*MockIManagerService)(nil).DeleteEmployeeByID), id)
}

// GetAllEmployees mocks base method.
func (m *MockIManagerService) GetAllEmployees() ([]models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllEmployees")
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllEmployees indicates an expected call of GetAllEmployees.
func (mr *MockIManagerServiceMockRecorder) GetAllEmployees() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllEmployees", reflect.TypeOf((*MockIManagerService)(nil).GetAllEmployees))
}

// GetAvailableStaffByTaskType mocks base method.
func (m *MockIManagerService) GetAvailableStaffByTaskType(arg0 string) ([]models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableStaffByTaskType", arg0)
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableStaffByTaskType indicates an expected call of GetAvailableStaffByTaskType.
func (mr *MockIManagerServiceMockRecorder) GetAvailableStaffByTaskType(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableStaffByTaskType", reflect.TypeOf((*MockIManagerService)(nil).GetAvailableStaffByTaskType), arg0)
}

// GetHotelReport mocks base method.
func (m *MockIManagerService) GetHotelReport() (*models.HotelReport, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHotelReport")
	ret0, _ := ret[0].(*models.HotelReport)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHotelReport indicates an expected call of GetHotelReport.
func (mr *MockIManagerServiceMockRecorder) GetHotelReport() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHotelReport", reflect.TypeOf((*MockIManagerService)(nil).GetHotelReport))
}

// GetTotalEmployees mocks base method.
func (m *MockIManagerService) GetTotalEmployees() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalEmployees")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalEmployees indicates an expected call of GetTotalEmployees.
func (mr *MockIManagerServiceMockRecorder) GetTotalEmployees() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalEmployees", reflect.TypeOf((*MockIManagerService)(nil).GetTotalEmployees))
}

// UpdateEmployeeAvailability mocks base method.
func (m *MockIManagerService) UpdateEmployeeAvailability(email string, available bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEmployeeAvailability", email, available)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEmployeeAvailability indicates an expected call of UpdateEmployeeAvailability.
func (mr *MockIManagerServiceMockRecorder) UpdateEmployeeAvailability(email, available any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEmployeeAvailability", reflect.TypeOf((*MockIManagerService)(nil).UpdateEmployeeAvailability), email, available)
}

// ViewAllFeedback mocks base method.
func (m *MockIManagerService) ViewAllFeedback() ([]models.Feedback, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ViewAllFeedback")
	ret0, _ := ret[0].([]models.Feedback)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ViewAllFeedback indicates an expected call of ViewAllFeedback.
func (mr *MockIManagerServiceMockRecorder) ViewAllFeedback() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ViewAllFeedback", reflect.TypeOf((*MockIManagerService)(nil).ViewAllFeedback))
}
