// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=../../mocks/mock_serviceRequestRepository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/meshyampratap01/letStayInn/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockServiceRequestRepository is a mock of ServiceRequestRepository interface.
type MockServiceRequestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockServiceRequestRepositoryMockRecorder
	isgomock struct{}
}

// MockServiceRequestRepositoryMockRecorder is the mock recorder for MockServiceRequestRepository.
type MockServiceRequestRepositoryMockRecorder struct {
	mock *MockServiceRequestRepository
}

// NewMockServiceRequestRepository creates a new mock instance.
func NewMockServiceRequestRepository(ctrl *gomock.Controller) *MockServiceRequestRepository {
	mock := &MockServiceRequestRepository{ctrl: ctrl}
	mock.recorder = &MockServiceRequestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceRequestRepository) EXPECT() *MockServiceRequestRepositoryMockRecorder {
	return m.recorder
}

// GetAssignedServiceRequests mocks base method.
func (m *MockServiceRequestRepository) GetAssignedServiceRequests(employeeID string) ([]models.ServiceRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAssignedServiceRequests", employeeID)
	ret0, _ := ret[0].([]models.ServiceRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAssignedServiceRequests indicates an expected call of GetAssignedServiceRequests.
func (mr *MockServiceRequestRepositoryMockRecorder) GetAssignedServiceRequests(employeeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAssignedServiceRequests", reflect.TypeOf((*MockServiceRequestRepository)(nil).GetAssignedServiceRequests), employeeID)
}

// GetServiceRequestByReqID mocks base method.
func (m *MockServiceRequestRepository) GetServiceRequestByReqID(id string) (*models.ServiceRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceRequestByReqID", id)
	ret0, _ := ret[0].(*models.ServiceRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceRequestByReqID indicates an expected call of GetServiceRequestByReqID.
func (mr *MockServiceRequestRepositoryMockRecorder) GetServiceRequestByReqID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceRequestByReqID", reflect.TypeOf((*MockServiceRequestRepository)(nil).GetServiceRequestByReqID), id)
}

// GetServiceRequestByRoomNum mocks base method.
func (m *MockServiceRequestRepository) GetServiceRequestByRoomNum(roomNum int) (*models.ServiceRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServiceRequestByRoomNum", roomNum)
	ret0, _ := ret[0].(*models.ServiceRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceRequestByRoomNum indicates an expected call of GetServiceRequestByRoomNum.
func (mr *MockServiceRequestRepositoryMockRecorder) GetServiceRequestByRoomNum(roomNum any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceRequestByRoomNum", reflect.TypeOf((*MockServiceRequestRepository)(nil).GetServiceRequestByRoomNum), roomNum)
}

// GetUnassignedRequests mocks base method.
func (m *MockServiceRequestRepository) GetUnassignedRequests() ([]models.ServiceRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnassignedRequests")
	ret0, _ := ret[0].([]models.ServiceRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnassignedRequests indicates an expected call of GetUnassignedRequests.
func (mr *MockServiceRequestRepositoryMockRecorder) GetUnassignedRequests() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnassignedRequests", reflect.TypeOf((*MockServiceRequestRepository)(nil).GetUnassignedRequests))
}

// LoadServiceRequests mocks base method.
func (m *MockServiceRequestRepository) LoadServiceRequests() ([]models.ServiceRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadServiceRequests")
	ret0, _ := ret[0].([]models.ServiceRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadServiceRequests indicates an expected call of LoadServiceRequests.
func (mr *MockServiceRequestRepositoryMockRecorder) LoadServiceRequests() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadServiceRequests", reflect.TypeOf((*MockServiceRequestRepository)(nil).LoadServiceRequests))
}

// SaveServiceRequest mocks base method.
func (m *MockServiceRequestRepository) SaveServiceRequest(req models.ServiceRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveServiceRequest", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveServiceRequest indicates an expected call of SaveServiceRequest.
func (mr *MockServiceRequestRepositoryMockRecorder) SaveServiceRequest(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveServiceRequest", reflect.TypeOf((*MockServiceRequestRepository)(nil).SaveServiceRequest), req)
}

// UpdateIsAssigned mocks base method.
func (m *MockServiceRequestRepository) UpdateIsAssigned(reqID string, isAssigned bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIsAssigned", reqID, isAssigned)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateIsAssigned indicates an expected call of UpdateIsAssigned.
func (mr *MockServiceRequestRepositoryMockRecorder) UpdateIsAssigned(reqID, isAssigned any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIsAssigned", reflect.TypeOf((*MockServiceRequestRepository)(nil).UpdateIsAssigned), reqID, isAssigned)
}

// UpdateServiceRequest mocks base method.
func (m *MockServiceRequestRepository) UpdateServiceRequest(req *models.ServiceRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateServiceRequest", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateServiceRequest indicates an expected call of UpdateServiceRequest.
func (mr *MockServiceRequestRepositoryMockRecorder) UpdateServiceRequest(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateServiceRequest", reflect.TypeOf((*MockServiceRequestRepository)(nil).UpdateServiceRequest), req)
}
