// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=../../mocks/mock_roomRepository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/meshyampratap01/letStayInn/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockIRoomRepository is a mock of IRoomRepository interface.
type MockIRoomRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRoomRepositoryMockRecorder
	isgomock struct{}
}

// MockIRoomRepositoryMockRecorder is the mock recorder for MockIRoomRepository.
type MockIRoomRepositoryMockRecorder struct {
	mock *MockIRoomRepository
}

// NewMockIRoomRepository creates a new mock instance.
func NewMockIRoomRepository(ctrl *gomock.Controller) *MockIRoomRepository {
	mock := &MockIRoomRepository{ctrl: ctrl}
	mock.recorder = &MockIRoomRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRoomRepository) EXPECT() *MockIRoomRepositoryMockRecorder {
	return m.recorder
}

// AddRoom mocks base method.
func (m *MockIRoomRepository) AddRoom(room models.Room) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRoom", room)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRoom indicates an expected call of AddRoom.
func (mr *MockIRoomRepositoryMockRecorder) AddRoom(room any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRoom", reflect.TypeOf((*MockIRoomRepository)(nil).AddRoom), room)
}

// DeleteRoomByNumber mocks base method.
func (m *MockIRoomRepository) DeleteRoomByNumber(number int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRoomByNumber", number)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRoomByNumber indicates an expected call of DeleteRoomByNumber.
func (mr *MockIRoomRepositoryMockRecorder) DeleteRoomByNumber(number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRoomByNumber", reflect.TypeOf((*MockIRoomRepository)(nil).DeleteRoomByNumber), number)
}

// GetAllRooms mocks base method.
func (m *MockIRoomRepository) GetAllRooms() ([]models.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllRooms")
	ret0, _ := ret[0].([]models.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllRooms indicates an expected call of GetAllRooms.
func (mr *MockIRoomRepositoryMockRecorder) GetAllRooms() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllRooms", reflect.TypeOf((*MockIRoomRepository)(nil).GetAllRooms))
}

// GetAvailableRooms mocks base method.
func (m *MockIRoomRepository) GetAvailableRooms() ([]models.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableRooms")
	ret0, _ := ret[0].([]models.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableRooms indicates an expected call of GetAvailableRooms.
func (mr *MockIRoomRepositoryMockRecorder) GetAvailableRooms() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableRooms", reflect.TypeOf((*MockIRoomRepository)(nil).GetAvailableRooms))
}

// GetRoomNumberByBookingID mocks base method.
func (m *MockIRoomRepository) GetRoomNumberByBookingID(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomNumberByBookingID", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoomNumberByBookingID indicates an expected call of GetRoomNumberByBookingID.
func (mr *MockIRoomRepositoryMockRecorder) GetRoomNumberByBookingID(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomNumberByBookingID", reflect.TypeOf((*MockIRoomRepository)(nil).GetRoomNumberByBookingID), arg0)
}

// RoomExists mocks base method.
func (m *MockIRoomRepository) RoomExists(number int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoomExists", number)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RoomExists indicates an expected call of RoomExists.
func (mr *MockIRoomRepositoryMockRecorder) RoomExists(number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoomExists", reflect.TypeOf((*MockIRoomRepository)(nil).RoomExists), number)
}

// SaveRooms mocks base method.
func (m *MockIRoomRepository) SaveRooms(rooms []models.Room) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRooms", rooms)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRooms indicates an expected call of SaveRooms.
func (mr *MockIRoomRepositoryMockRecorder) SaveRooms(rooms any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRooms", reflect.TypeOf((*MockIRoomRepository)(nil).SaveRooms), rooms)
}
