// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=../../mocks/mock_employeeService.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/meshyampratap01/letStayInn/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockIEmployeeService is a mock of IEmployeeService interface.
type MockIEmployeeService struct {
	ctrl     *gomock.Controller
	recorder *MockIEmployeeServiceMockRecorder
	isgomock struct{}
}

// MockIEmployeeServiceMockRecorder is the mock recorder for MockIEmployeeService.
type MockIEmployeeServiceMockRecorder struct {
	mock *MockIEmployeeService
}

// NewMockIEmployeeService creates a new mock instance.
func NewMockIEmployeeService(ctrl *gomock.Controller) *MockIEmployeeService {
	mock := &MockIEmployeeService{ctrl: ctrl}
	mock.recorder = &MockIEmployeeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIEmployeeService) EXPECT() *MockIEmployeeServiceMockRecorder {
	return m.recorder
}

// GetAssignedServiceRequests mocks base method.
func (m *MockIEmployeeService) GetAssignedServiceRequests(employeeID string) ([]models.ServiceRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAssignedServiceRequests", employeeID)
	ret0, _ := ret[0].([]models.ServiceRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAssignedServiceRequests indicates an expected call of GetAssignedServiceRequests.
func (mr *MockIEmployeeServiceMockRecorder) GetAssignedServiceRequests(employeeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAssignedServiceRequests", reflect.TypeOf((*MockIEmployeeService)(nil).GetAssignedServiceRequests), employeeID)
}

// GetAvailability mocks base method.
func (m *MockIEmployeeService) GetAvailability(userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailability", userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailability indicates an expected call of GetAvailability.
func (mr *MockIEmployeeServiceMockRecorder) GetAvailability(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailability", reflect.TypeOf((*MockIEmployeeService)(nil).GetAvailability), userID)
}

// GetRoomNumberByBookingID mocks base method.
func (m *MockIEmployeeService) GetRoomNumberByBookingID(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomNumberByBookingID", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoomNumberByBookingID indicates an expected call of GetRoomNumberByBookingID.
func (mr *MockIEmployeeServiceMockRecorder) GetRoomNumberByBookingID(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomNumberByBookingID", reflect.TypeOf((*MockIEmployeeService)(nil).GetRoomNumberByBookingID), arg0)
}

// ToggleAvailability mocks base method.
func (m *MockIEmployeeService) ToggleAvailability(userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToggleAvailability", userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ToggleAvailability indicates an expected call of ToggleAvailability.
func (mr *MockIEmployeeServiceMockRecorder) ToggleAvailability(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToggleAvailability", reflect.TypeOf((*MockIEmployeeService)(nil).ToggleAvailability), userID)
}

// UpdateServiceRequestStatus mocks base method.
func (m *MockIEmployeeService) UpdateServiceRequestStatus(requestID string, newStatus models.ServiceStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateServiceRequestStatus", requestID, newStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateServiceRequestStatus indicates an expected call of UpdateServiceRequestStatus.
func (mr *MockIEmployeeServiceMockRecorder) UpdateServiceRequestStatus(requestID, newStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateServiceRequestStatus", reflect.TypeOf((*MockIEmployeeService)(nil).UpdateServiceRequestStatus), requestID, newStatus)
}
