// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=../../mocks/mock_bookingService.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/meshyampratap01/letStayInn/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockIBookingService is a mock of IBookingService interface.
type MockIBookingService struct {
	ctrl     *gomock.Controller
	recorder *MockIBookingServiceMockRecorder
	isgomock struct{}
}

// MockIBookingServiceMockRecorder is the mock recorder for MockIBookingService.
type MockIBookingServiceMockRecorder struct {
	mock *MockIBookingService
}

// NewMockIBookingService creates a new mock instance.
func NewMockIBookingService(ctrl *gomock.Controller) *MockIBookingService {
	mock := &MockIBookingService{ctrl: ctrl}
	mock.recorder = &MockIBookingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIBookingService) EXPECT() *MockIBookingServiceMockRecorder {
	return m.recorder
}

// BookRoom mocks base method.
func (m *MockIBookingService) BookRoom(ctx context.Context, roomNum int, checkInStr, checkOutStr string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BookRoom", ctx, roomNum, checkInStr, checkOutStr)
	ret0, _ := ret[0].(error)
	return ret0
}

// BookRoom indicates an expected call of BookRoom.
func (mr *MockIBookingServiceMockRecorder) BookRoom(ctx, roomNum, checkInStr, checkOutStr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BookRoom", reflect.TypeOf((*MockIBookingService)(nil).BookRoom), ctx, roomNum, checkInStr, checkOutStr)
}

// CancelBooking mocks base method.
func (m *MockIBookingService) CancelBooking(ctx context.Context, bookingID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelBooking", ctx, bookingID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CancelBooking indicates an expected call of CancelBooking.
func (mr *MockIBookingServiceMockRecorder) CancelBooking(ctx, bookingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelBooking", reflect.TypeOf((*MockIBookingService)(nil).CancelBooking), ctx, bookingID)
}

// GetActiveBookings mocks base method.
func (m *MockIBookingService) GetActiveBookings() ([]models.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveBookings")
	ret0, _ := ret[0].([]models.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveBookings indicates an expected call of GetActiveBookings.
func (mr *MockIBookingServiceMockRecorder) GetActiveBookings() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveBookings", reflect.TypeOf((*MockIBookingService)(nil).GetActiveBookings))
}

// GetBookingIDByRoomNumber mocks base method.
func (m *MockIBookingService) GetBookingIDByRoomNumber(roomNumber int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookingIDByRoomNumber", roomNumber)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookingIDByRoomNumber indicates an expected call of GetBookingIDByRoomNumber.
func (mr *MockIBookingServiceMockRecorder) GetBookingIDByRoomNumber(roomNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingIDByRoomNumber", reflect.TypeOf((*MockIBookingService)(nil).GetBookingIDByRoomNumber), roomNumber)
}

// GetRoomByNumber mocks base method.
func (m *MockIBookingService) GetRoomByNumber(roomNum int) (*models.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomByNumber", roomNum)
	ret0, _ := ret[0].(*models.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoomByNumber indicates an expected call of GetRoomByNumber.
func (mr *MockIBookingServiceMockRecorder) GetRoomByNumber(roomNum any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomByNumber", reflect.TypeOf((*MockIBookingService)(nil).GetRoomByNumber), roomNum)
}

// GetUserActiveBookings mocks base method.
func (m *MockIBookingService) GetUserActiveBookings(ctx context.Context) ([]models.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserActiveBookings", ctx)
	ret0, _ := ret[0].([]models.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserActiveBookings indicates an expected call of GetUserActiveBookings.
func (mr *MockIBookingServiceMockRecorder) GetUserActiveBookings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserActiveBookings", reflect.TypeOf((*MockIBookingService)(nil).GetUserActiveBookings), ctx)
}

// IsRoomBooked mocks base method.
func (m *MockIBookingService) IsRoomBooked(roomNumber int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRoomBooked", roomNumber)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsRoomBooked indicates an expected call of IsRoomBooked.
func (mr *MockIBookingServiceMockRecorder) IsRoomBooked(roomNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRoomBooked", reflect.TypeOf((*MockIBookingService)(nil).IsRoomBooked), roomNumber)
}
